name: charmed-openstack-upgrader
base: core22
version: '0.1'
summary: Charmed Openstack Upgrader
license: Apache-2.0
description: |
  Snap for automatically upgrading Charmed Openstack and related
  components.

grade: devel
confinement: strict

apps:
  cou:
    command: bin/cou.wrapper
    aliases: [ cou ]
    plugs:
      - juju-client-observe
      - network
      - network-bind
      - dot-local-share-juju
      - local-cou

parts:
  cou-wrapper:
    plugin: dump
    source: bin
    organize:
      cou.wrapper: bin/cou.wrapper

  cou:
    plugin: python
    build-packages:
      - python3-wheel
      - python3-pip
      - python3-setuptools-scm
    source: .
    stage-packages:
      - git
      - openssh-client

plugs:
  dot-local-share-juju:
    interface: personal-files
    write:
      - $HOME/.local/share/juju
  local-cou:
    interface: personal-files
    write:
      - $HOME/.local/share/cou
