name: charmed-openstack-upgrader
base: core22
adopt-info: cou
summary: Charmed Openstack Upgrader
license: Apache-2.0
description: |
  Snap for automatically upgrading Charmed Openstack and related
  components.

grade: devel
confinement: strict

apps:
  cou:
    command: bin/cou.wrapper
    plugs:
      - juju-client-observe
      - network
      - network-bind
      - dot-local-cou

parts:
  cou-wrapper:
    plugin: dump
    source: bin
    organize:
      cou.wrapper: bin/cou.wrapper

  cou:
    plugin: python
    build-packages:
      - python3-wheel
      - python3-pip
      - python3-setuptools-scm
    source: .
    stage-packages:
      - git
      - openssh-client
    override-build: |
        craftctl default
        set -e
        VERSION=$(python3 setup.py --version)
        echo "Version: ${VERSION}"
        craftctl set version=${VERSION}

plugs:
  dot-local-cou:
    interface: personal-files
    write:
      - $HOME/.local/share/cou
