name: charmed-openstack-upgrader
base: core22
adopt-info: cou
summary: Charmed Openstack Upgrader
license: Apache-2.0
description: |
  Snap for automatically upgrading Canonical Charmed Openstack and related
  components.

grade: devel
confinement: strict

apps:
  cou:
    command: bin/cou.wrapper
    completer: etc/bash_completion.d/snap.cou
    plugs:
      - juju-client-observe
      - network
      - network-bind
      - dot-local-share-cou

parts:
  cou-wrapper:
    plugin: dump
    source: bin
    organize:
      cou.wrapper: bin/cou.wrapper

  cou:
    plugin: python
    build-packages:
      - python3-wheel
      - python3-pip
      - python3-setuptools-scm
    source: .
    stage-packages:
      - git
      - openssh-client
    override-build: |
      craftctl default
      set -e

      # set up bash completion
      mkdir -p ${CRAFT_PART_INSTALL}/etc/bash_completion.d/
      echo 'export PATH="${PATH}:/snap/bin:/var/lib/snapd/snap/bin"' > ${CRAFT_PART_INSTALL}/etc/bash_completion.d/snap.cou
      cat ../src/completions/bash/cou_bash_completion >> ${CRAFT_PART_INSTALL}/etc/bash_completion.d/snap.cou

      # set version
      VERSION=$(python3 setup.py --version)
      echo "Version: ${VERSION}"
      craftctl set version=${VERSION}

plugs:
  dot-local-share-cou:
    interface: personal-files
    write:
      - $HOME/.local/share/cou
