name: Mocked Plans Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - '**.rst'

concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

jobs:
  mocked-plans:
    name: Mocked plans
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install 'tox<5'

    - name: Run mocked-plans tests
      run: |
        pip install '.[unittests]'
        PYTHONPATH=$(pwd) pytest ./tests/mocked_plans/ -s -vv
