# This is a template `pr.yaml` file for snaps
# This file is managed by bootstack-charms-spec and should not be modified
# within individual snap repos. https://launchpad.net/bootstack-charms-spec

name: PR workflow running lint checkers, unit and functional tests

concurrency:
  group: ${{ github.workflow }}

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  lint-unit:
    name: Lint checkers and unit tests
    uses: canonical/bootstack-actions/.github/workflows/_lint-unit.yaml@main
    secrets: inherit
    with:
      python-version: "['3.10']"
      tox-version: ""
      working-directory: "."

  func:
    name: Functional tests
    runs-on: self-hosted
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox<4"
      - name: Run func tests
        run: make functional
