name: TICS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tics-analysis:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install coverage tools
        run: |
          pip install coverage

      - name: Download unit test coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-unit
          path: ./artifacts
        continue-on-error: true  # Don’t fail if artifact is missing

      - name: Download functional test coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-functional
          path: ./artifacts
        continue-on-error: true  # Don’t fail if artifact is missing

      - name: Merge coverage reports
        run: |
          # Find all coverage files (if any exist)
          coverage_files=""
          if [ -f ./artifacts/coverage-unit.xml ]; then
            coverage_files="$coverage_files ./artifacts/coverage-unit.xml"
          fi
          if [ -f ./artifacts/coverage-functional.xml ]; then
            coverage_files="$coverage_files ./artifacts/coverage-functional.xml"
          fi

          if [ -n "$coverage_files" ]; then
            echo "Merging coverage files: $coverage_files"
            coverage combine $coverage_files
            coverage xml -o tests/report/coverage.xml
          else
            echo "No coverage files found, skipping merge"
            touch tests/report/coverage.xml  # Create an empty file to avoid downstream failure
          fi

      - name: Run TICS analysis
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: charmed-openstack-upgrader
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
