name: TICS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  tics-analysis:
    runs-on: ubuntu-22.04
    needs: check
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install coverage tools
        run: |
          pip install coverage

      - name: Determine system architecture
        run: echo "SYSTEM_ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Download Coverage Files
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*-${{ env.SYSTEM_ARCH }}
          merge-multiple: true
          path: artifacts/
        continue-on-error: true  # Don’t fail if artifact is missing

      - name: Merge coverage reports
        run: |
          # Create the path that is expected to have a coverage.xml for tics
          mkdir -p tests/report/

          coverage_files=""
          for file in ./artifacts/coverage-*; do
            if [ -f "$file" ]; then
              coverage_files="$coverage_files $file"
            fi
          done

          if [ -n "$coverage_files" ]; then
            echo "Merging coverage files: $coverage_files"
            coverage combine $coverage_files
            coverage xml -o tests/report/coverage.xml
          else
            echo "No coverage files found, skipping merge"
            # Create an empty file to avoid downstream failure
            touch tests/report/merged-coverage.xml
          fi

      - name: Run TICS analysis
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: charmed-openstack-upgrader
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
