name: TICS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  check:
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  tics-analysis:
    runs-on: ubuntu-22.04
    needs: check
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install coverage tools
        run: |
          pip install coverage

      - name: Download unit test coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-unit
          path: .coverage-files/
        continue-on-error: true  # Don’t fail if artifact is missing

      - name: Download functional test coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-functional
          path: .coverage-files/
        continue-on-error: true  # Don’t fail if artifact is missing

      - name: Merge coverage reports
        run: |
          ls .coverage-files/
          mkdir -p tests/report/
          coverage combine .coverage-files
          coverage xml -o tests/report/coverage.xml
          coverage report

      - name: Run TICS analysis
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: charmed-openstack-upgrader
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
